version: '3.3'

volumes:
  postgres_volume:

services:
  postgres-mentoring:
    image: postgres:latest
    container_name: postgres-mentoring
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: mentoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s9td3ixh
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
