server:
  port: ${LINK_SHORTENER_PORT:8080}
  servlet:
    context-path: /${spring.application.name}

spring:
  profiles:
    active: log-exec-time
  application:
    name: link-shortener
  datasource:
    url: jdbc:postgresql://localhost:5433/mentoring
    username: postgres
    password: s9td3ixh
    hikari:
      schema: link_shortener
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate

link-shortener:
  short-link-length: 8

logging:
  log-exec-time: true
  web-logging:
    enabled: true
    log-body: true
    masked-headers:
      - authorization
      - cookie
