apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-shortener-deployment
  namespace: lshort
  labels:
    app: link-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: link-shortener
  template:
    metadata:
      labels:
        app: link-shortener
    spec:
      containers:
        - name: link-shortener
          image: link-shortener:1.0
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
