apiVersion: v1
kind: Service
metadata:
  name: link-shortener-service
  namespace: lshort
spec:
  type: NodePort
  selector:
    app: link-shortener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
